export const SOLIDLETTERS = {
  letter1: require('../../assets/solid/ls01.png'), // statically analyzed
  letter2: require('../../assets/solid/ls02.png'), 
  letter3: require('../../assets/solid/ls03.png'), 
  letter4: require('../../assets/solid/ls04.png'), 
  letter5: require('../../assets/solid/ls05.png'), 
  letter6: require('../../assets/solid/ls06.png'), 
  letter7: require('../../assets/solid/ls07.png'), 
  letter8: require('../../assets/solid/ls08.png'), 
  letter9: require('../../assets/solid/ls09.png'), 
  letter10: require('../../assets/solid/ls10.png'), 
  letter11: require('../../assets/solid/ls11.png'), 
  letter12: require('../../assets/solid/ls12.png'), 
  letter13: require('../../assets/solid/ls13.png'), 
  letter14: require('../../assets/solid/ls14.png'), 
  letter15: require('../../assets/solid/ls15.png'), 
  letter16: require('../../assets/solid/ls16.png'), 
  letter17: require('../../assets/solid/ls17.png'),
  letter18: require('../../assets/solid/ls18.png'), 
  letter19: require('../../assets/solid/ls19.png'), 
  letter20: require('../../assets/solid/ls20.png'), 
  letter21: require('../../assets/solid/ls21.png'), 
  letter22: require('../../assets/solid/ls22.png'), 
  letter23: require('../../assets/solid/ls23.png'), 
  letter24: require('../../assets/solid/ls24.png'),
  letter25: require('../../assets/solid/ls25.png'), 
  letter26: require('../../assets/solid/ls26.png'), 
  letter27: require('../../assets/solid/ls27.png'), 
  letter28: require('../../assets/solid/ls28.png'), 
  letter29: require('../../assets/solid/ls29.png'), 
  letter30: require('../../assets/solid/ls30.png'), 
  letter31: require('../../assets/solid/ls31.png'),
  letter32: require('../../assets/solid/ls32.png'), 
  letter33: require('../../assets/solid/ls33.png'), 
  letter34: require('../../assets/solid/ls34.png'), 
  letter35: require('../../assets/solid/ls35.png'), 
  letter36: require('../../assets/solid/ls36.png'), 
  letter37: require('../../assets/solid/ls37.png'), 
  letter38: require('../../assets/solid/ls38.png'),
  letter39: require('../../assets/solid/ls39.png'), 
  letter40: require('../../assets/solid/ls40.png'), 
  letter41: require('../../assets/solid/ls41.png'), 
  

}
export const OUTLINEDLETTERS = {
  letter1: require('../../assets/outline/lo01.png'), // statically analyzed
  letter2: require('../../assets/outline/lo02.png'), 
  letter3: require('../../assets/outline/lo03.png'), 
  letter4: require('../../assets/outline/lo04.png'), 
  letter5: require('../../assets/outline/lo05.png'), 
  letter6: require('../../assets/outline/lo06.png'), 
  letter7: require('../../assets/outline/lo07.png'), 
  letter8: require('../../assets/outline/lo08.png'), 
  letter9: require('../../assets/outline/lo09.png'), 
  letter10: require('../../assets/outline/lo10.png'), 
  letter11: require('../../assets/outline/lo11.png'), 
  letter12: require('../../assets/outline/lo12.png'), 
  letter13: require('../../assets/outline/lo13.png'), 
  letter14: require('../../assets/outline/lo14.png'), 
  letter15: require('../../assets/outline/lo15.png'), 
  letter16: require('../../assets/outline/lo16.png'), 
  letter17: require('../../assets/outline/lo17.png'),
  letter18: require('../../assets/outline/lo18.png'), 
  letter19: require('../../assets/outline/lo19.png'), 
  letter20: require('../../assets/outline/lo20.png'), 
  letter21: require('../../assets/outline/lo21.png'), 
  letter22: require('../../assets/outline/lo22.png'), 
  letter23: require('../../assets/outline/lo23.png'), 
  letter24: require('../../assets/outline/lo24.png'),
  letter25: require('../../assets/outline/lo25.png'), 
  letter26: require('../../assets/outline/lo26.png'), 
  letter27: require('../../assets/outline/lo27.png'), 
  letter28: require('../../assets/outline/lo28.png'), 
  letter29: require('../../assets/outline/lo29.png'), 
  letter30: require('../../assets/outline/lo30.png'), 
  letter31: require('../../assets/outline/lo31.png'),
  letter32: require('../../assets/outline/lo32.png'), 
  letter33: require('../../assets/outline/lo33.png'), 
  letter34: require('../../assets/outline/lo34.png'), 
  letter35: require('../../assets/outline/lo35.png'), 
  letter36: require('../../assets/outline/lo36.png'), 
  letter37: require('../../assets/outline/lo37.png'), 
  letter38: require('../../assets/outline/lo38.png'),
  letter39: require('../../assets/outline/lo39.png'), 
  letter40: require('../../assets/outline/lo40.png'), 
  letter41: require('../../assets/outline/lo41.png'),
}

export const IMAGES = {
  AppLogo: require('../../assets/images/AppLogo.png'),
  AppLogoUpdated: require('../../assets/images/AppLogoUpdated.png'), // statically analyzed
  BlankOpeningScreen: require('../../assets/images/BlankOpeningScreen.png'),
  BugIcon: require('../../assets/images/BugIcon.png'),
  FlipCard: require('../../assets/images/FlipCard.png'),
  GoBack: require('../../assets/images/GoBack.png'),
  LoopAudio: require('../../assets/images/LoopAudio.png'),
  NextWord: require('../../assets/images/NextWord.png'),
  OpeningScreen: require('../../assets/images/OpeningScreen.png'),
  PauseAudio: require('../../assets/images/PauseAudio.png'),
  PlayAudio: require('../../assets/images/PlayAudio.png'),
  PreviousWord: require('../../assets/images/PreviousWord.png'),
  SettingsIcon: require('../../assets/images/SettingsIcon.png'),
  StarHollow: require('../../assets/images/StarHollow.png'),
  StarSolid: require('../../assets/images/StarSolid.png'),
}