export const vocabularyData = {
    "Family":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਖੁਸ਼', starred: false, english:'happy', audioId:'voc0201'},
                { id:2, gender: '', punjabi:'ਦੋਵੇਂ', starred: false, english:'both', audioId:'voc0202'},
                { id:3, gender: '', punjabi:'ਇਕੱਠੇ', starred: false, english:'together', audioId:'voc0203'},
                { id:4, gender: '', punjabi:'ਵੱਡਾ', starred: false, english:'big or older', audioId:'voc0204'},
                { id:5, gender: '', punjabi:'ਛੋਟਾ', starred: false, english:'small or younger', audioId:'voc0205'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਘਰ', starred: false, english:'home', audioId:'voc0206'},
                { id:2, gender: 'f', punjabi:'ਗੱਲਬਾਤ', starred: false, english:'conversation', audioId:'voc0207'},
                { id:3, gender: 'm', punjabi:'ਪਿਆਰ', starred: false, english:'love', audioId:'voc0208'},
                { id:4, gender: 'm', punjabi:'ਕੰਮ', starred: false, english:'work', audioId:'voc0209'},
                { id:5, gender: 'f', punjabi:'ਮਦਦ', starred: false, english:'help', audioId:'voc0210'},
                { id:6, gender: 'm', punjabi:'ਬਜ਼ੁਰਗ', starred: false, english:'elder', audioId:'voc0211'},
                { id:7, gender: 'm', punjabi:'ਡਾਕਟਰ', starred: false, english:'physician', audioId:'voc0212'},
                { id:8, gender: 'm', punjabi:'ਅਧਿਆਪਕ', starred: false, english:'teacher', audioId:'voc0213'},
                { id:9, gender: 'm', punjabi:'ਸਕੂਲ', starred: false, english:'school', audioId:'voc0214'},
                { id:10, gender: 'f', punjabi:'ਸੈਰ', starred: false, english:'stroll', audioId:'voc0215'},
                { id:11, gender: 'm', punjabi:'ਰਿਸ਼ਤੇਦਾਰ', starred: false, english:'relatives', audioId:'voc0216'},
                { id:12, gender: 'm', punjabi:'ਪਰਿਵਾਰ', starred: false, english:'family', audioId:'voc0217'},
                { id:13, gender: 'm', punjabi:'ਜੀਅ', starred: false, english:'family members', audioId:'voc0218'},
                { id:14, gender: 'f', punjabi:'ਮਾਤਾ/ਮਾਂ', starred: false, english:'mother', audioId:'voc0219'},
                { id:15, gender: 'm', punjabi:'ਪਿਤਾ', starred: false, english:'father', audioId:'voc0220'},
                { id:16, gender: 'm', punjabi:'ਭਰਾ', starred: false, english:'brother', audioId:'voc0221'},
                { id:17, gender: 'f', punjabi:'ਭੈਣ', starred: false, english:'sister', audioId:'voc0222'},
                { id:18, gender: 'f', punjabi:'ਧੀ', starred: false, english:'daughter', audioId:'voc0223'},
                { id:19, gender: 'm', punjabi:'ਪੁੱਤਰ', starred: false, english:'son', audioId:'voc0224'},
                { id:20, gender: 'm', punjabi:'ਪਤੀ', starred: false, english:'husband', audioId:'voc0225'},
                { id:21, gender: 'f', punjabi:'ਪਤਨੀ', starred: false, english:'wife', audioId:'voc0226'},
                { id:22, gender: 'f', punjabi:'ਨਾਨੀ', starred: false, english:'maternal grandmother', audioId:'voc0227'},
                { id:23, gender: 'm', punjabi:'ਨਾਨਾ', starred: false, english:'maternal grandfather', audioId:'voc0228'},
                { id:24, gender: 'f', punjabi:'ਮਾਸੀ', starred: false, english:'mother’s sister', audioId:'voc0229'},
                { id:25, gender: 'm', punjabi:'ਮਾਮਾ', starred: false, english:'mother’s brother', audioId:'voc0230'},
                { id:26, gender: 'f', punjabi:'ਮਾਮੀ', starred: false, english:'mama’s wife', audioId:'voc0231'},
                { id:27, gender: 'f', punjabi:'ਦਾਦੀ', starred: false, english:'paternal grandmother', audioId:'voc0232'},
                { id:28, gender: 'm', punjabi:'ਦਾਦਾ', starred: false, english:'paternal grandfather', audioId:'voc0233'},
                { id:29, gender: 'm', punjabi:'ਚਾਚਾ', starred: false, english:'father’s younger brother', audioId:'voc0234'},
                { id:30, gender: 'f', punjabi:'ਚਾਚੀ', starred: false, english:'chacha’s wife', audioId:'voc0235'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਹੋਣਾ', starred: false, english:'to be', audioId:'voc0236'},
                { id:2, gender: '', punjabi:'ਕਰਨਾ', starred: false, english:'to do', audioId:'voc0237'},
                { id:3, gender: '', punjabi:'ਖੇਡਣਾ', starred: false, english:'to play', audioId:'voc0238'},
                { id:4, gender: '', punjabi:'ਪੜ੍ਹਨਾ', starred: false, english:'to study or read', audioId:'voc0239'},
            ]
    },
    "Home":
    {
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਐਤਵਾਰ', starred: false, english:'Sunday', audioId:'voc0301'},
                { id:2, gender: 'm', punjabi:'ਸੋਮਵਾਰ', starred: false, english:'Monday', audioId:'voc0302'},
                { id:3, gender: 'm', punjabi:'ਮੰਗਲਵਾਰ', starred: false, english:'Tuesday', audioId:'voc0303'},
                { id:4, gender: 'm', punjabi:'ਬੁੱਧਵਾਰ', starred: false, english:'Wednesday', audioId:'voc0304'},
                { id:5, gender: 'm', punjabi:'ਵੀਰਵਾਰ', starred: false, english:'Thursday', audioId:'voc0305'},
                { id:6, gender: 'm', punjabi:'ਸ਼ੁੱਕਰਵਾਰ', starred: false, english:'Friday', audioId:'voc0306'},
                { id:7, gender: 'm', punjabi:'ਸ਼ਨਿੱਚਰਵਾਰ', starred: false, english:'Saturday', audioId:'voc0307'},
                { id:8, gender: '', punjabi:'ਅਪਾਰਟਮੈਂਟ', starred: false, english:'apartment', audioId:'voc0308'},
                { id:9, gender: 'm', punjabi:'ਕਮਰਾ', starred: false, english:'room', audioId:'voc0309'},
                { id:10, gender: 'f', punjabi:'ਥਾਂ', starred: false, english:'space, place', audioId:'voc0310'},
                { id:11, gender: 'f', punjabi:'ਬੈਠਕ', starred: false, english:'sitting room', audioId:'voc0311'},
                { id:12, gender: 'f', punjabi:'ਰਸੋਈ', starred: false, english:'kitchen', audioId:'voc0312'},
                { id:13, gender: 'm', punjabi:'ਬੈੱਡਰੂਮ', starred: false, english:'bedroom', audioId:'voc0313'},
                { id:14, gender: 'm', punjabi:'ਗ਼ੁਸਲਖ਼ਾਨਾ', starred: false, english:'bathroom', audioId:'voc0314'},
                { id:15, gender: 'm', punjabi:'ਵਿਹੜਾ', starred: false, english:'yard', audioId:'voc0315'},
                { id:16, gender: 'f', punjabi:'ਸੜਕ', starred: false, english:'road, street', audioId:'voc0316'},
                { id:17, gender: 'f', punjabi:'ਛੱਤ', starred: false, english:'roof, ceiling', audioId:'voc0317'},
                { id:18, gender: 'm', punjabi:'ਦਰਵਾਜਾ', starred: false, english:'door', audioId:'voc0318'},
                { id:19, gender: 'f', punjabi:'ਖਿੜਕੀ', starred: false, english:'window', audioId:'voc0319'},
                { id:20, gender: 'f', punjabi:'ਚਾਹ', starred: false, english:'tea', audioId:'voc0320'},
                { id:21, gender: '', punjabi:'ਫਰਨੀਚਰ', starred: false, english:'furniture', audioId:'voc0321'},
                { id:22, gender: '', punjabi:'ਬੁਰਸ਼', starred: false, english:'brush', audioId:'voc0322'},
                { id:23, gender: 'm', punjabi:'ਕੱਪੜੇ', starred: false, english:'clothes', audioId:'voc0323'},
                { id:24, gender: 'm', punjabi:'ਨਾਸ਼ਤਾ', starred: false, english:'breakfast', audioId:'voc0324'},
                { id:25, gender: 'f', punjabi:'ਸਫ਼ਾਈ', starred: false, english:'cleanliness', audioId:'voc0325'},
                { id:26, gender: 'm', punjabi:'ਅਰਾਮ', starred: false, english:'rest', audioId:'voc0326'},
                { id:27, gender: 'f', punjabi:'ਰਾਤ', starred: false, english:'night', audioId:'voc0327'},
                { id:28, gender: 'f', punjabi:'ਸਵੇਰ', starred: false, english:'morning', audioId:'voc0328'},
                { id:29, gender: 'f', punjabi:'ਸ਼ਾਮ', starred: false, english:'evening', audioId:'voc0329'},
                { id:30, gender: 'f', punjabi:'ਦੁਪਹਿਰ', starred: false, english:'at noon', audioId:'voc0330'},
                { id:31, gender: '', punjabi:'ਵਜੇ', starred: false, english:'o clock', audioId:'voc0332'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਜਾਗਣਾ', starred: false, english:'to wake up', audioId:'voc0333'},
                { id:2, gender: '', punjabi:'ਬੈਠਣਾ', starred: false, english:'to sit', audioId:'voc0334'},
                { id:3, gender: '', punjabi:'ਦੇਖਣਾ', starred: false, english:'to see', audioId:'voc0335'},
                { id:4, gender: '', punjabi:'ਖਾਣਾ', starred: false, english:'to eat', audioId:'voc0336'},
                { id:5, gender: '', punjabi:'ਜਾਣਾ', starred: false, english:'to go', audioId:'voc0337'},
                { id:6, gender: '', punjabi:'ਧੋਣਾ', starred: false, english:'to wash', audioId:'voc0338'},
                { id:7, gender: '', punjabi:'ਸੌਣਾ', starred: false, english:'to sleep', audioId:'voc0339'},
                { id:8, gender: '', punjabi:'ਆਉਣਾ', starred: false, english:'to come', audioId:'voc0340'},
                { id:9, gender: '', punjabi:'ਨਹਾਉਣਾ', starred: false, english:'to take a shower', audioId:'voc0341'},
                { id:10, gender: '', punjabi:'ਬਣਾਉਣਾ', starred: false, english:'to make', audioId:'voc0342'},
                { id:11, gender: '', punjabi:'ਚਲਾਉਣਾ', starred: false, english:'to start or drive', audioId:'voc0343'},
                { id:12, gender: '', punjabi:'ਰਹਿਣਾ', starred: false, english:'to live', audioId:'voc0344'},
            ]
    },
    "Body & Health":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਤੰਦਰੁਸਤ', starred: false, english:'healthy', audioId:'voc0430'},
                { id:2, gender: '', punjabi:'ਉਦਾਸ', starred: false, english:'sad', audioId:'voc0431'},
                { id:3, gender: '', punjabi:'ਬਿਮਾਰ', starred: false, english:'sick', audioId:'voc0432'},
                { id:4, gender: '', punjabi:'ਢਿੱਲਾ', starred: false, english:'unwell', audioId:'voc0433'},
                { id:5, gender: '', punjabi:'ਕਮਜ਼ੋਰ', starred: false, english:'weak', audioId:'voc0434'},
            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਗੁੱਸਾ', starred: false, english:'anger', audioId:'voc0401'},
                { id:2, gender: 'f', punjabi:'ਘਬਰਾਹਟ', starred: false, english:'anxiety', audioId:'voc0402'},
                { id:3, gender: 'f', punjabi:'ਬੇਚੈਨੀ', starred: false, english:'restlessness', audioId:'voc0403'},
                { id:4, gender: '', punjabi:'ਸਟਰੈੱਸ', starred: false, english:'stress', audioId:'voc0404'},
                { id:5, gender: '', punjabi:'ਟੈਨਸ਼ਨ', starred: false, english:'tension', audioId:'voc0405'},
                { id:6, gender: 'm', punjabi:'ਫ਼ਿਕਰ', starred: false, english:'worry', audioId:'voc0406'},
                { id:7, gender: 'm', punjabi:'ਜ਼ੁਕਾਮ', starred: false, english:'bad cold', audioId:'voc0407'},
                { id:8, gender: 'f', punjabi:'ਠੰਢ', starred: false, english:'cold', audioId:'voc0408'},
                { id:9, gender: 'f', punjabi:'ਖੰਘ', starred: false, english:'cough', audioId:'voc0409'},
                { id:10, gender: 'm', punjabi:'ਥਕਾਵਟ', starred: false, english:'fatigue', audioId:'voc0410'},
                { id:11, gender: 'm', punjabi:'ਬੁਖਾਰ', starred: false, english:'fever', audioId:'voc0411'},
                { id:12, gender: 'f', punjabi:'ਛਿੱਕ', starred: false, english:'sneeze', audioId:'voc0412'},
                { id:13, gender: 'f', punjabi:'ਜਾਂਚ', starred: false, english:'diagnosis', audioId:'voc0413'},
                { id:14, gender: 'f', punjabi:'ਸਿਰ ਦਰਦ', starred: false, english:'headache', audioId:'voc0414'},
                { id:15, gender: 'f', punjabi:'ਸਿਹਤ', starred: false, english:'health', audioId:'voc0415'},
                { id:16, gender: 'm', punjabi:'ਦਿਲ', starred: false, english:'heart', audioId:'voc0416'},
                { id:17, gender: 'f', punjabi:'ਗਰਮੀ', starred: false, english:'heat, summer', audioId:'voc0417'},
                { id:18, gender: 'f', punjabi:'ਭੁੱਖ', starred: false, english:'hunger', audioId:'voc0418'},
                { id:19, gender: 'f', punjabi:'ਦਵਾਈ', starred: false, english:'medicine', audioId:'voc0419'},
                { id:20, gender: 'm', punjabi:'ਮਨ', starred: false, english:'mind', audioId:'vvoc0420'},
                { id:21, gender: 'f', punjabi:'ਗੋਲੀ', starred: false, english:'pill', audioId:'voc0421'},
                { id:22, gender: 'f', punjabi:'ਤ੍ਰੇਹ', starred: false, english:'thirst', audioId:'voc0422'},
                { id:23, gender: 'f', punjabi:'ਨੀਂਦ', starred: false, english:'sleep', audioId:'voc0423'},
                { id:24, gender: 'm', punjabi:'ਖਿਆਲ', starred: false, english:'thought', audioId:'voc0424'},
                { id:25, gender: 'm', punjabi:'ਗਲਾ', starred: false, english:'throat', audioId:'voc0425'},
                { id:26, gender: 'm', punjabi:'ਇਲਾਜ', starred: false, english:'treatment', audioId:'voc0426'},
                { id:27, gender: 'f', punjabi:'ਅੱਖਾਂ', starred: false, english:'eyes', audioId:'voc0427'},
                { id:28, gender: 'm', punjabi:'ਜੀਵਨ', starred: false, english:'life', audioId:'voc0428'},
                { id:29, gender: 'f', punjabi:'ਮਾਸਪੇਸ਼ੀਆਂ', starred: false, english:'muscle', audioId:'voc0429'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਰੋਣਾ', starred: false, english:'to cry', audioId:'voc0435'},
                { id:2, gender: '', punjabi:'ਪੀਣਾ', starred: false, english:'to drink', audioId:'voc0436'},
                { id:3, gender: '', punjabi:'ਦਿਲ ਕਰਨਾ', starred: false, english:'to feel like', audioId:'voc0437'},
                { id:4, gender: '', punjabi:'ਲੱਗਣਾ', starred: false, english:'to feel, appear or seem', audioId:'voc0438'},
                { id:5, gender: '', punjabi:'ਦੁਖਣਾ', starred: false, english:'To hurt', audioId:'voc0439'},
                { id:6, gender: '', punjabi:'ਹੋਣਾ', starred: false, english:'to occur', audioId:'voc0440'},
                { id:7, gender: '', punjabi:'ਲੈਣਾ', starred: false, english:'to take', audioId:'voc0441'},
            ]
    },
    "Market & Food":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਚੌਥਾ ਹਿੱਸਾ', starred: false, english:'one fourth', audioId:'voc0531'},
                { id:2, gender: '', punjabi:'ਤੀਜਾ ਹਿੱਸਾ', starred: false, english:'one third', audioId:'voc0532'},
                { id:3, gender: '', punjabi:'ਪੂਰਾ', starred: false, english:'full/all', audioId:'voc0533'},
                { id:4, gender: '', punjabi:'ਅੱਧਾ', starred: false, english:'half', audioId:'voc0534'},
                { id:5, gender: '', punjabi:'ਘੱਟ', starred: false, english:'less', audioId:'voc0535'},
                { id:6, gender: '', punjabi:'ਵੱਧ', starred: false, english:'more than', audioId:'voc0536'},
                { id:7, gender: '', punjabi:'ਤਾਜ਼ਾ', starred: false, english:'fresh', audioId:'voc0537'},
                { id:8, gender: '', punjabi:'ਮਸਾਲੇਦਾਰ', starred: false, english:'spicy', audioId:'voc0538'},
                { id:9, gender: '', punjabi:'ਤੰਦੂਰੀ', starred: false, english:'tandoori (cooked in a clay oven)', audioId:'voc0539'},
                { id:10, gender: '', punjabi:'ਸੁਆਦ', starred: false, english:'delicious', audioId:'voc0540'},
                { id:11, gender: '', punjabi:'ਸਸਤਾ', starred: false, english:'cheap/inexpensive', audioId:'voc0541'},
                { id:12, gender: '', punjabi:'ਮਹਿੰਗਾ', starred: false, english:'expensive', audioId:'voc0542'},

            ],
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਮੱਖਣ', starred: false, english:'butter', audioId:'voc0501'},
                { id:2, gender: 'f', punjabi:'ਮੈਂਗੋ ਲੱਸੀ', starred: false, english:'mango buttermilk', audioId:'voc0502'},
                { id:3, gender: 'm', punjabi:'ਘਿਓ', starred: false, english:'clarified butter', audioId:'voc0503'},
                { id:4, gender: 'm', punjabi:'ਪਕੌੜਾ', starred: false, english:'fritters', audioId:'voc0504'},
                { id:5, gender: 'm', punjabi:'ਫਲ', starred: false, english:'fruit', audioId:'voc0505'},
                { id:6, gender: 'm', punjabi:'ਪਨੀਰ', starred: false, english:'cheese', audioId:'voc0506'},
                { id:7, gender: 'm', punjabi:'ਪਰੌਂਠਾ', starred: false, english:'pan fried flat bread', audioId:'voc0507'},
                { id:8, gender: 'f', punjabi:'ਮੱਕੀ ਦੀ ਰੋਟੀ', starred: false, english:'corn tortilla', audioId:'voc0508'},
                { id:9, gender: 'f', punjabi:'ਰੋਟੀ', starred: false, english:'flour tortilla', audioId:'voc0509'},
                { id:10, gender: 'm', punjabi:'ਦਹੀਂ', starred: false, english:'yogurt', audioId:'voc0510'},
                { id:11, gender: 'f', punjabi:'ਦਾਲ', starred: false, english:'lentil (dish)', audioId:'voc0511'},
                { id:12, gender: 'm', punjabi:'ਚੌਲ', starred: false, english:'rice', audioId:'voc0512'},
                { id:13, gender: 'm', punjabi:'ਪਿਆਜ', starred: false, english:'onion', audioId:'voc0513'},
                { id:14, gender: 'm', punjabi:'ਮਟਰ', starred: false, english:'pea', audioId:'voc0514'},
                { id:15, gender: 'm', punjabi:'ਆਲੂ', starred: false, english:'potato', audioId:'voc0515'},
                { id:16, gender: 'm', punjabi:'ਸਾਗ', starred: false, english:'spinach and mustard greens dish', audioId:'voc0516'},
                { id:17, gender: 'm', punjabi:'ਟਮਾਟਰ', starred: false, english:'tomato', audioId:'voc0517'},
                { id:18, gender: 'f', punjabi:'ਸਬਜ਼ੀ', starred: false, english:'vegetable', audioId:'voc0518'},
                { id:19, gender: 'm', punjabi:'ਹਰਾ ਧਨੀਆ', starred: false, english:'cilantro', audioId:'voc0519'},
                { id:20, gender: 'm', punjabi:'ਲਸਣ', starred: false, english:'garlic', audioId:'voc0520'},
                { id:21, gender: 'm', punjabi:'ਅਦਰਕ', starred: false, english:'ginger', audioId:'voc0521'},
                { id:22, gender: 'f', punjabi:'ਲਾਲ ਮਿਰਚ', starred: false, english:'red chili', audioId:'voc0522'},
                { id:23, gender: 'm', punjabi:'ਲੂਣ', starred: false, english:'salt', audioId:'voc0523'},
                { id:24, gender: 'm', punjabi:'ਗਰਮ ਮਸਾਲਾ', starred: false, english:'spice mix', audioId:'voc0524'},
                { id:25, gender: 'f', punjabi:'ਹਲਦੀ', starred: false, english:'turmeric', audioId:'voc0525'},
                { id:26, gender: 'm', punjabi:'ਰੰਗ', starred: false, english:'color', audioId:'voc0526'},
                { id:27, gender: 'f', punjabi:'ਦੁਕਾਨ', starred: false, english:'store', audioId:'voc0527'},
                { id:28, gender: 'm', punjabi:'ਦੁਕਾਨਦਾਰ', starred: false, english:'storekeeper', audioId:'voc0528'},
                { id:29, gender: 'm', punjabi:'ਗਾਹਕ', starred: false, english:'customer', audioId:'voc0529'},
                { id:30, gender: 'm', punjabi:'ਤੜਕਾ', starred: false, english:'tadka (tempered spices in heated oil)', audioId:'voc0530'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਚਾਹੁਣਾ', starred: false, english:'to need/to want', audioId:'voc0543'},
                { id:2, gender: '', punjabi:'ਪਾਉਣਾ', starred: false, english:'to add', audioId:'voc0544'},
                { id:3, gender: '', punjabi:'ਪੁੱਛਣਾ', starred: false, english:'to ask', audioId:'voc0545'},
                { id:4, gender: '', punjabi:'ਲਿਆਉਣਾ', starred: false, english:'to bring', audioId:'voc0546'},
                { id:5, gender: '', punjabi:'ਖਰੀਦਣਾ', starred: false, english:'to buy', audioId:'voc0547'},
                { id:6, gender: '', punjabi:'ਕੱਟਣਾ', starred: false, english:'to cut', audioId:'voc0548'},
                { id:7, gender: '', punjabi:'ਤਲਨਾ', starred: false, english:'to deep fry', audioId:'voc0549'},
                { id:8, gender: '', punjabi:'ਦੇਣਾ', starred: false, english:'to give', audioId:'voc0550'},
                { id:9, gender: '', punjabi:'ਪਕਾਉਣਾ', starred: false, english:'to cook', audioId:'voc0551'},
                { id:10, gender: '', punjabi:'ਖਰਚਣਾ', starred: false, english:'to spend', audioId:'voc0552'},
                { id:7, gender: '', punjabi:'ਭੁੰਨਣਾ', starred: false, english:'to roast', audioId:'voc0553'},
                { id:8, gender: '', punjabi:'ਪਸੰਦ ਹੋਣਾ', starred: false, english:'to be liked', audioId:'voc0554'},

            ]
    },
    "Faith & Celebrations":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਇਕ ਦੂਸਰੇ ਨੂੰ', starred: false, english:'each other', audioId:'voc0653'},
                { id:2, gender: '', punjabi:'ਮਸ਼ਹੂਰ', starred: false, english:'famous', audioId:'voc0654'},
                { id:3, gender: '', punjabi:'ਨਵਾਂ', starred: false, english:'new', audioId:'voc0655'},
                { id:4, gender: '', punjabi:'ਸਭ ਤੋਂ ਵਧੀਆ', starred: false, english:'the best', audioId:'voc0656'},
                { id:5, gender: '', punjabi:'ਹਜ਼ਾਰਾਂ', starred: false, english:'thousands', audioId:'voc0657'},
                { id:6, gender: '', punjabi:'ਬੁਰਾ', starred: false, english:'bad/evil', audioId:'voc0658'},
                          
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਮੇਲਾ', starred: false, english:'fair', audioId:'voc0601'},
                { id:2, gender: 'f', punjabi:'ਰੌਣਕ', starred: false, english:'festive crowd', audioId:'voc0602'},
                { id:3, gender: 'f', punjabi:'ਭੀੜ', starred: false, english:'crowd', audioId:'voc0603'},
                { id:4, gender: 'm', punjabi:'ਖਾਣ-ਪੀਣ', starred: false, english:'eat/drink', audioId:'voc0604'},
                { id:5, gender: 'f', punjabi:'ਮਸਤੀ', starred: false, english:'enjoyment', audioId:'voc0605'},
                { id:6, gender: 'm', punjabi:'ਤਿਉਹਾਰ', starred: false, english:'festival', audioId:'voc0606'},
                { id:7, gender: 'f', punjabi:'ਆਤਿਸ਼ਬਾਜ਼ੀ', starred: false, english:'fireworks display', audioId:'voc0607'},
                { id:8, gender: 'm', punjabi:'ਪਟਾਕੇ', starred: false, english:'fireworks', audioId:'voc0608'},
                { id:9, gender: 'm', punjabi:'ਤੋਹਫ਼ਾ', starred: false, english:'gift', audioId:'voc0609'},
                { id:10, gender: 'm', punjabi:'ਲੋਕ', starred: false, english:'people', audioId:'voc0610'},
                { id:11, gender: 'm', punjabi:'ਧੂਮਧਾਮ', starred: false, english:'enthusiasm', audioId:'voc0611'},
                { id:12, gender: 'm', punjabi:'ਧਰਮ', starred: false, english:'religion', audioId:'voc0612'},
                { id:13, gender: 'f', punjabi:'ਸੰਗਤ', starred: false, english:'congregation', audioId:'voc0613'},
                { id:14, gender: 'm', punjabi:'ਗੁਰਦੁਆਰਾ', starred: false, english:'Sikh place of worship', audioId:'voc0614'},
                { id:15, gender: 'm', punjabi:'ਹੋਲਾ ਮਹੱਲਾ', starred: false, english:'Sikh spring festival', audioId:'voc0615'},
                { id:16, gender: 'f', punjabi:'ਵਿਸਾਖੀ', starred: false, english:'Punjabi harvest festival', audioId:'voc0616'},
                { id:17, gender: 'm', punjabi:'ਕੀਰਤਨ', starred: false, english:'devotional singing', audioId:'voc0617'},
                { id:18, gender: 'm', punjabi:'ਲੰਗਰ', starred: false, english:'community meal', audioId:'voc0618'},
                { id:19, gender: 'f', punjabi:'ਪੂਜਾ', starred: false, english:'Hindu prayer', audioId:'voc0619'},
                { id:20, gender: 'f', punjabi:'ਅਰਦਾਸ', starred: false, english:'Sikh prayer', audioId:'voc0620'},
                { id:21, gender: 'f', punjabi:'ਦੁਆ', starred: false, english:'Muslim prayer', audioId:'voc0621'},
                { id:22, gender: 'm', punjabi:'ਮੰਦਰ', starred: false, english:'temple', audioId:'voc0622'},
                { id:23, gender: 'f', punjabi:'ਮਸਜਿਦ', starred: false, english:'mosque', audioId:'voc0623'},
                { id:24, gender: 'm', punjabi:'ਰਮਜ਼ਾਨ', starred: false, english:'Muslim holy month', audioId:'voc0624'},
                { id:25, gender: 'm', punjabi:'ਰੋਜ਼ਾ', starred: false, english:'Muslim fasting during Ramzan', audioId:'voc0625'},
                { id:26, gender: 'm', punjabi:'ਬੱਚਾ', starred: false, english:'child', audioId:'voc0626'},
                { id:27, gender: 'f', punjabi:'ਔਰਤ', starred: false, english:'woman', audioId:'voc0627'},
                { id:28, gender: 'm', punjabi:'ਆਦਮੀ', starred: false, english:'man', audioId:'voc0628'},
                { id:29, gender: 'f', punjabi:'ਮੋਮਬੱਤੀ', starred: false, english:'candle', audioId:'voc0629'},
                { id:30, gender: 'm', punjabi:'ਦੀਵਾ', starred: false, english:'clay lamp', audioId:'voc0630'},
                { id:31, gender: 'f', punjabi:'ਚੜ੍ਹਦੀ ਕਲਾ', starred: false, english:'eternal optimism', audioId:'voc0631'},
                { id:32, gender: 'm', punjabi:'ਮਹੀਨਾ', starred: false, english:'month', audioId:'voc0632'},
                { id:33, gender: 'm', punjabi:'ਮੌਸਮ', starred: false, english:'weather', audioId:'voc0633'},
                { id:34, gender: 'f', punjabi:'ਰੋਸ਼ਨੀ', starred: false, english:'light', audioId:'voc0634'},
                { id:35, gender: 'm', punjabi:'ਚੰਨ', starred: false, english:'moon', audioId:'voc0635'},
                { id:36, gender: 'f', punjabi:'ਜਿੱਤ', starred: false, english:'victory', audioId:'voc0636'},
                { id:37, gender: 'f', punjabi:'ਹਾਰ', starred: false, english:'defeat', audioId:'voc0637'},
                { id:38, gender: 'm', punjabi:'ਹਨੇਰਾ', starred: false, english:'darkness', audioId:'voc0638'},
                { id:39, gender: 'f', punjabi:'ਸਜਾਵਟ', starred: false, english:'decoration', audioId:'voc0639'},
                { id:40, gender: 'm', punjabi:'ਨਜ਼ਾਰਾ', starred: false, english:'view', audioId:'voc0640'},
                { id:41, gender: 'f', punjabi:'ਬੱਤੀ', starred: false, english:'lantern/wick/light', audioId:'voc0641'},
                { id:42, gender: 'f', punjabi:'ਲੜੀ', starred: false, english:'string', audioId:'voc0642'},
                { id:43, gender: 'm', punjabi:'ਬੂਹਾ', starred: false, english:'door', audioId:'voc0643'},
                { id:44, gender: 'f', punjabi:'ਬਾਰੀ', starred: false, english:'window', audioId:'voc0644'},
                { id:45, gender: 'm', punjabi:'ਗੁਰੂ ਗ੍ਰੰਥ ਸਾਹਿਬ', starred: false, english:'Sikh holy scripture', audioId:'voc0645'},
                { id:46, gender: 'm', punjabi:'ਵਾਹਿਗੁਰੂ', starred: false, english:'God (Sikh)', audioId:'voc0646'},
                { id:47, gender: 'm', punjabi:'ਭਗਵਾਨ', starred: false, english:'God (Hindu)', audioId:'voc0647'},
                { id:48, gender: 'm', punjabi:'ਅੱਲਾਹ', starred: false, english:'God (Muslim)', audioId:'voc0648'},
                { id:49, gender: 'm', punjabi:'ਰੱਬ', starred: false, english:'God (Universal)', audioId:'voc0649'},
                { id:50, gender: 'm', punjabi:'ਸਿੱਖ', starred: false, english:'Sikh', audioId:'voc0650'},
                { id:51, gender: 'm', punjabi:'ਹਿੰਦੂ', starred: false, english:'Hindu', audioId:'voc0651'},
                { id:52, gender: 'm', punjabi:'ਮੁਸਲਮਾਨ', starred: false, english:'Muslim', audioId:'voc0652'},
         
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਮਨਾਉਣਾ', starred: false, english:'to celebrate', audioId:'voc0659'},
                { id:2, gender: '', punjabi:'ਸਜਾਉਣਾ', starred: false, english:'to decorate', audioId:'voc0660'},
                { id:3, gender: '', punjabi:'ਜਗਾਉਣਾ', starred: false, english:'to light up', audioId:'voc0661'},
                { id:4, gender: '', punjabi:'ਰੱਖਣਾ', starred: false, english:'to keep', audioId:'voc0662'},
                { id:5, gender: '', punjabi:'ਕਹਿਣਾ', starred: false, english:'to say', audioId:'voc0663'},
                { id:6, gender: '', punjabi:'ਤੋੜਨਾ', starred: false, english:'to break', audioId:'voc0664'},
                { id:7, gender: '', punjabi:'ਚੜ੍ਹਨਾ', starred: false, english:'to rise', audioId:'voc0665'},
                { id:8, gender: '', punjabi:'ਵਾਪਸ ਕਰਨਾ', starred: false, english:'to return', audioId:'voc0666'},
                { id:9, gender: '', punjabi:'ਜਗਮਗ ਕਰਨਾ', starred: false, english:'to sparkle', audioId:'voc0667'},
            ]
    },
    "Clothes & Fashion":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਸਾਫ਼', starred: false, english:'clean', audioId:'voc0730'},
                { id:2, gender: '', punjabi:'ਸੂਤੀ', starred: false, english:'cotton', audioId:'voc0731'},
                { id:3, gender: '', punjabi:'ਗੂੜ੍ਹਾ', starred: false, english:'dark', audioId:'voc0732'},
                { id:4, gender: '', punjabi:'ਗੰਦਾ', starred: false, english:'dirty', audioId:'voc0733'},
                { id:5, gender: '', punjabi:'ਮੋਟਾ', starred: false, english:'fat', audioId:'voc0734'},
                { id:6, gender: '', punjabi:'ਪਤਲਾ', starred: false, english:'skinny/thin', audioId:'voc0735'},
                { id:7, gender: '', punjabi:'ਫਿੱਕਾ', starred: false, english:'light in color or quantity', audioId:'voc0736'},
                { id:8, gender: '', punjabi:'ਲੰਮਾ', starred: false, english:'long/tall', audioId:'voc0737'},
                { id:9, gender: '', punjabi:'ਖੁੱਲ੍ਹਾ', starred: false, english:'loose/open', audioId:'voc0738'},
                { id:10, gender: '', punjabi:'ਭੀੜਾ', starred: false, english:'tight', audioId:'voc0739'},
                { id:11, gender: '', punjabi:'ਢੁੱਕਵਾਂ', starred: false, english:'matching', audioId:'voc0740'},
                { id:12, gender: '', punjabi:'ਪੁਰਾਣਾ', starred: false, english:'old', audioId:'voc0741'},
                { id:13, gender: '', punjabi:'ਸਾਦਾ', starred: false, english:'simple', audioId:'voc0742'},
                { id:14, gender: '', punjabi:'ਸੋਹਣਾ', starred: false, english:'beautiful', audioId:'voc0743'},
                { id:15, gender: '', punjabi:'ਰੇਸ਼ਮੀ', starred: false, english:'silky', audioId:'voc0744'},
                { id:16, gender: '', punjabi:'ਇੱਕੋ-ਜਿਹੇ', starred: false, english:'similar', audioId:'voc0745'},
                { id:17, gender: '', punjabi:'ਵੱਖਰਾ', starred: false, english:'different', audioId:'voc0746'},
                { id:18, gender: '', punjabi:'ਲਾਲ', starred: false, english:'red', audioId:'voc0747'},
                { id:19, gender: '', punjabi:'ਸੰਤਰੀ', starred: false, english:'orange', audioId:'voc0748'},
                { id:20, gender: '', punjabi:'ਪੀਲਾ', starred: false, english:'yellow', audioId:'voc0749'},
                { id:21, gender: '', punjabi:'ਹਰਾ', starred: false, english:'green', audioId:'voc0750'},
                { id:22, gender: '', punjabi:'ਨੀਲਾ', starred: false, english:'blue', audioId:'voc0751'},
                { id:23, gender: '', punjabi:'ਗੁਲਾਬੀ', starred: false, english:'pink', audioId:'voc0752'},
                { id:24, gender: '', punjabi:'ਕਾਲਾ', starred: false, english:'black', audioId:'voc0753'},
                { id:25, gender: '', punjabi:'ਚਿੱਟਾ', starred: false, english:'white', audioId:'voc0754'},
                { id:26, gender: '', punjabi:'ਭੂਰਾ', starred: false, english:'brown', audioId:'voc0755'},
                { id:27, gender: '', punjabi:'ਸੁਨਹਿਰੀ', starred: false, english:'golden', audioId:'voc0756'},
                { id:28, gender: '', punjabi:'ਜਾਮਨੀ', starred: false, english:'purple', audioId:'voc0757'},
                { id:29, gender: '', punjabi:'ਫ਼ਿਰੋਜ਼ੀ', starred: false, english:'turquoise', audioId:'voc0758'},
                { id:30, gender: '', punjabi:'ਸਲੇਟੀ', starred: false, english:'gray', audioId:'voc0759'},
                { id:31, gender: '', punjabi:'ਬਦਾਮੀ', starred: false, english:'almond color', audioId:'voc0760'},
                { id:32, gender: '', punjabi:'ਮੋਰ-ਪੰਖੀਆ', starred: false, english:'peacock color', audioId:'voc0761'},
            
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਬਾਂਹ', starred: false, english:'arm/sleeve', audioId:'voc0701'},
                { id:2, gender: 'f', punjabi:'ਚੁੰਨੀ', starred: false, english:'long scarf', audioId:'voc0702'},
                { id:3, gender: 'f', punjabi:'ਟੋਪੀ', starred: false, english:'hat', audioId:'voc0703'},
                { id:4, gender: 'm', punjabi:'ਹਿਜਾਬ', starred: false, english:'Muslim women’s head covering', audioId:'voc0704'},
                { id:5, gender: 'm', punjabi:'ਲਹਿੰਗਾ', starred: false, english:'Indian outfit with a long skirt', audioId:'voc0705'},
                { id:6, gender: 'm', punjabi:'ਕੁੜਤਾ ਪਜਾਮਾ', starred: false, english:'Indian men’s outfit', audioId:'voc0706'},
                { id:7, gender: 'f', punjabi:'ਪਜਾਮੀ', starred: false, english:'leggings', audioId:'voc0707'},
                { id:8, gender: 'f', punjabi:'ਫੁਲਕਾਰੀ', starred: false, english:'Punjabi embroidery style', audioId:'voc0708'},
                { id:9, gender: 'm', punjabi:'ਪਲਾਜ਼ੋ', starred: false, english:'women’s loose pants', audioId:'voc0709'},
                { id:10, gender: 'f', punjabi:'ਸਲਵਾਰ', starred: false, english:'pleated baggy pants', audioId:'voc0710'},
                { id:11, gender: 'f', punjabi:'ਕਮੀਜ਼', starred: false, english:'shirt', audioId:'voc0711'},
                { id:12, gender: 'f', punjabi:'ਜੁੱਤੀ', starred: false, english:'shoe', audioId:'voc0712'},
                { id:13, gender: 'm', punjabi:'ਸੂਟ', starred: false, english:'long shirt with baggy pants', audioId:'voc0713'},
                { id:14, gender: 'f', punjabi:'ਪੱਗ/ਦਸਤਾਰ', starred: false, english:'turban', audioId:'voc0714'},
                { id:15, gender: 'f', punjabi:'ਚੂੜੀ', starred: false, english:'bangle', audioId:'voc0715'},
                { id:16, gender: 'f', punjabi:'ਬਿੰਦੀ', starred: false, english:'dot worn on the forehead', audioId:'voc0716'},
                { id:17, gender: 'm', punjabi:'ਟਿੱਕਾ', starred: false, english:'jewelry worn on the forehead', audioId:'voc0717'},
                { id:18, gender: 'm', punjabi:'ਕਾਂਟੇ', starred: false, english:'dangling earrings', audioId:'voc0718'},
                { id:19, gender: 'f', punjabi:'ਵਾਲੀਆਂ', starred: false, english:'earrings', audioId:'voc0719'},
                { id:20, gender: 'm', punjabi:'ਹਾਰ', starred: false, english:'necklace', audioId:'voc0720'},
                { id:21, gender: 'f', punjabi:'ਅਲਮਾਰੀ', starred: false, english:'closet/cabinet', audioId:'voc0721'},
                { id:22, gender: 'm', punjabi:'ਪਰੈੱਸ', starred: false, english:'iron', audioId:'voc0722'},
                { id:23, gender: 'm', punjabi:'ਮੇਚਾ', starred: false, english:'size', audioId:'voc0723'},
                { id:24, gender: 'm', punjabi:'ਦਾਗ਼', starred: false, english:'stain', audioId:'voc0724'},
                { id:25, gender: 'm', punjabi:'ਰਿਵਾਜ਼', starred: false, english:'trend', audioId:'voc0725'},
                { id:26, gender: 'f', punjabi:'ਮੰਗਣੀ', starred: false, english:'engagement', audioId:'voc0726'},
                { id:27, gender: '', punjabi:'ਮੰਗੇਤਰ', starred: false, english:'fiance', audioId:'voc0727'},
                { id:28, gender: 'm', punjabi:'ਵਿਆਹ', starred: false, english:'wedding', audioId:'voc0728'},
                { id:29, gender: 'f', punjabi:'ਜ਼ਰੂਰਤ', starred: false, english:'need', audioId:'voc0729'},
           
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਲੱਗਣਾ', starred: false, english:'to appear', audioId:'voc0762'},
                { id:2, gender: '', punjabi:'ਬਦਲਣਾ', starred: false, english:'to change', audioId:'voc0763'},
                { id:3, gender: '', punjabi:'ਤਿਆਰ ਹੋਣਾ', starred: false, english:'to get ready', audioId:'voc0764'},
                { id:4, gender: '', punjabi:'ਜਚਣਾ', starred: false, english:'to look good', audioId:'voc0765'},
                { id:5, gender: '', punjabi:'ਪਾਉਣਾ', starred: false, english:'to wear', audioId:'voc0766'},
                { id:6, gender: '', punjabi:'ਭਰਨਾ', starred: false, english:'to fill', audioId:'voc0767'},
                { id:7, gender: '', punjabi:'ਕੋਲ ਹੋਣਾ', starred: false, english:'to have', audioId:'voc0768'},
            ],
    },
    "Daily Routines & Hobbies":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਔਖਾ', starred: false, english:'difficult', audioId:'voc0826'},
                { id:2, gender: '', punjabi:'ਸੌਖਾ', starred: false, english:'easy', audioId:'voc0827'},
                { id:3, gender: '', punjabi:'ਵਿਹਲਾ', starred: false, english:'not busy', audioId:'voc0828'},
                { id:4, gender: '', punjabi:'ਘਰੇਲੂ', starred: false, english:'household', audioId:'voc0829'},
                { id:5, gender: '', punjabi:'ਸਖ਼ਤ', starred: false, english:'hard', audioId:'voc0830'},
                { id:6, gender: '', punjabi:'ਮਿਹਨਤੀ', starred: false, english:'hard-working', audioId:'voc0831'},
                { id:7, gender: '', punjabi:'ਦਿਲਚਸਪ', starred: false, english:'interesting', audioId:'voc0832'},
                { id:8, gender: '', punjabi:'ਆਲਸੀ', starred: false, english:'lazy', audioId:'voc0833'},
                { id:9, gender: '', punjabi:'ਜ਼ਿਆਦਾ', starred: false, english:'more', audioId:'voc0834'},
                { id:10, gender: '', punjabi:'ਅਗਲਾ', starred: false, english:'next', audioId:'voc0835'},
                { id:11, gender: '', punjabi:'ਪਿਛਲਾ', starred: false, english:'last', audioId:'voc0836'},
                { id:12, gender: '', punjabi:'ਐਵੇਂ ਈ', starred: false, english:'for no reason', audioId:'voc0837'},
                { id:13, gender: '', punjabi:'ਡੇਢ', starred: false, english:'half past one', audioId:'voc0838'},
                { id:14, gender: '', punjabi:'ਢਾਈ', starred: false, english:'half past two', audioId:'voc0839'},
                { id:15, gender: '', punjabi:'ਸਵਾ', starred: false, english:'quarter past the hour', audioId:'voc0840'},
                { id:16, gender: '', punjabi:'ਪੌਣਾ', starred: false, english:'quarter to', audioId:'voc0841'},
                { id:17, gender: '', punjabi:'ਸਾਢੇ', starred: false, english:'half past', audioId:'voc0842'},
                { id:18, gender: '', punjabi:'ਵਜੇ', starred: false, english:'o’clock', audioId:'voc0843'},
                { id:19, gender: '', punjabi:'ਪੜ੍ਹਾਕੂ', starred: false, english:'studious', audioId:'voc0844'},
            ],
        Nouns:
            [
               // { id:*, gender: 'm', punjabi:'ਲੌਢਾ ਵੇਲਾ', starred: false, english:'afternoon', audioId:'voc0801'},
               // { id:*, gender: 'm', punjabi:'ਛਾਹ ਵੇਲਾ', starred: false, english:'breakfast', audioId:'voc0802'},
                { id:3, gender: 'f', punjabi:'ਛੁੱਟੀ', starred: false, english:'break', audioId:'voc0803'},
                { id:4, gender: 'm', punjabi:'ਪਰਸੋਂ', starred: false, english:'day before yesterday or day after tomorrow', audioId:'voc0804'},
                { id:5, gender: 'm', punjabi:'ਦਿਨ', starred: false, english:'day', audioId:'voc0805'},
                { id:6, gender: 'm', punjabi:'ਘੰਟਾ', starred: false, english:'hour', audioId:'voc0806'},
                { id:7, gender: 'm', punjabi:'ਮਿੰਟ', starred: false, english:'minute', audioId:'voc0807'},
                { id:8, gender: 'm', punjabi:'ਸਕਿੰਟ', starred: false, english:'second', audioId:'voc0808'},
                { id:9, gender: 'm', punjabi:'ਵੇਲਾ', starred: false, english:'time', audioId:'voc0809'},
                { id:10, gender: 'm', punjabi:'ਅੱਜ', starred: false, english:'today', audioId:'voc0810'},
                { id:11, gender: 'm', punjabi:'ਕੱਲ੍ਹ', starred: false, english:'tomorrow/yesterday', audioId:'voc0811'},
                { id:12, gender: '', punjabi:'ਦਹਾਕਾ', starred: false, english:'decade', audioId:'voc0812'},
                { id:13, gender: '', punjabi:'ਸਦੀ', starred: false, english:'century', audioId:'voc0813'},
                { id:14, gender: 'm', punjabi:'ਕਲੰਡਰ', starred: false, english:'calendar', audioId:'voc0814'},
                { id:15, gender: 'm', punjabi:'ਰੁਝੇਵਾਂ', starred: false, english:'busyness', audioId:'voc0815'},
                { id:16, gender: 'm', punjabi:'ਕੰਘਾ', starred: false, english:'comb', audioId:'voc0816'},
                { id:17, gender: 'f', punjabi:'ਸੇਵਾ', starred: false, english:'service, community service', audioId:'voc0817'},
                { id:18, gender: 'm', punjabi:'ਸ਼ੁਰੂ', starred: false, english:'start', audioId:'voc0818'},
                { id:19, gender: 'f', punjabi:'ਮਿਹਨਤ', starred: false, english:'hard work', audioId:'voc0819'},
                { id:20, gender: 'm', punjabi:'ਸ਼ੌਕ', starred: false, english:'hobby', audioId:'voc0820'},
                { id:21, gender: 'm', punjabi:'ਆਲਸ', starred: false, english:'laziness', audioId:'voc0821'},
                { id:22, gender: 'm', punjabi:'ਇਮਤਿਹਾਨ', starred: false, english:'test', audioId:'voc0822'},
                { id:23, gender: 'm', punjabi:'ਬਿਸਤਰਾ', starred: false, english:'bed', audioId:'voc0823'},
                { id:24, gender: 'm', punjabi:'ਦੋਸਤ', starred: false, english:'male friend', audioId:'voc0824'},
                { id:25, gender: 'f', punjabi:'ਸਹੇਲੀ', starred: false, english:'female friend', audioId:'voc0825'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਲਾਉਣਾ', starred: false, english:'to attend', audioId:'voc0845'},
                { id:2, gender: '', punjabi:'ਸਕਣਾ', starred: false, english:'to be able to do', audioId:'voc0846'},
                { id:3, gender: '', punjabi:'ਉੱਠਣਾ', starred: false, english:'to get up', audioId:'voc0847'},
                { id:4, gender: '', punjabi:'ਚੁੱਕਣਾ', starred: false, english:'to have already done, to lift, to pick up', audioId:'voc0848'},
                { id:5, gender: '', punjabi:'ਭੱਜ-ਦੌੜ ਕਰਨੀ', starred: false, english:'to run around', audioId:'voc0849'},
                { id:6, gender: '', punjabi:'ਚੱਲਣਾ', starred: false, english:'to go', audioId:'voc0850'},
                { id:7, gender: '', punjabi:'ਬਿਤਾਉਣਾ', starred: false, english:'to spend time', audioId:'voc0851'},
                { id:8, gender: '', punjabi:'ਨਿਕਲਣਾ', starred: false, english:'to get out/to leave', audioId:'voc0852'},
                { id:9, gender: '', punjabi:'ਘੁੰਮਣਾ-ਫਿਰਨਾ', starred: false, english:'to roam about', audioId:'voc0853'},
            ],
    },
   
}




/*
 "College Life":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਿਜੰਨਾ', starred: false, english:'as much', audioId:'voc0932'},
                { id:2, gender: '', punjabi:'ਮਦਦਗਾਰ', starred: false, english:'helpful', audioId:'voc0933'},
                { id:3, gender: '', punjabi:'ਘੱਟ ਿਗਣਤੀ', starred: false, english:'minority', audioId:'voc0934'},
                { id:4, gender: '', punjabi:'ਬਾਹਰਲਾ', starred: false, english:'outsider', audioId:'voc0935'},
                { id:5, gender: '', punjabi:'ਜੋ-ਭਰਪੂਰ', starred: false, english:'passionate/exuberant', audioId:'voc0936'},
                { id:6, gender: '', punjabi:'ਮਹੱਤਵਪੂਰਨ', starred: false, english:'significant', audioId:'voc0937'},
                { id:7, gender: '', punjabi:'ਇੰਨਾ', starred: false, english:'so much', audioId:'voc0938'},
                { id:8, gender: '', punjabi:'ਅੱਜ-ਕੱਲ', starred: false, english:'these days', audioId:'voc0939'},
                { id:9, gender: '', punjabi:'ਮੁੱਢਲੀਆਂ', starred: false, english:'undergraduate/elementary', audioId:'voc0940'},
                { id:10, gender: '', punjabi:'ਿਜੰਨਾ', starred: false, english:'as much', audioId:'voc0941'},
                { id:11, gender: '', punjabi:'ਮਦਦਗਾਰ', starred: false, english:'helpful', audioId:'voc0942'},
                { id:12, gender: '', punjabi:'ਘੱਟ ਿਗਣਤੀ', starred: false, english:'minority', audioId:'voc0943'},
                { id:13, gender: '', punjabi:'ਅਖੀਰਲਾ', starred: false, english:'last', audioId:'voc0944'},
                      
            ],
        Nouns:
            [
                { id:1, gender: 'f', punjabi:'ਅਰਜ਼ੀ', starred: false, english:'application', audioId:'voc0901'},
                { id:2, gender: 'm', punjabi:'ਇੰਤਜ਼ਾਮ', starred: false, english:'arrangement', audioId:'voc0902'},
                { id:3, gender: 'f', punjabi:'ਸੰਸਥਾ', starred: false, english:'association', audioId:'voc0903'},
                { id:4, gender: 'm', punjabi:'ਸੰਤੁਲਨ', starred: false, english:'balance', audioId:'voc0904'},
                { id:5, gender: 'm', punjabi:'ਫ਼ਾਇਦਾ', starred: false, english:'benefit', audioId:'voc0905'},
                { id:6, gender: 'f', punjabi:'ਸਭਾ', starred: false, english:'club', audioId:'voc0906'},
                { id:7, gender: '', punjabi:'ਕਿਮਉਿਨਟੀ', starred: false, english:'community', audioId:'voc0907'},
                { id:8, gender: 'm', punjabi:'ਸੰਪਰਕ', starred: false, english:'contact', audioId:'voc0908'},
                { id:9, gender: 'm', punjabi:'ਚੋਣਵ', starred: false, english:'elective', audioId:'voc0909'},
                { id:10, gender:'m', punjabi:'ਮਹੌਲ', starred: false, english:'environment/atmosphere', audioId:'voc0910'},
                { id:11, gender: 'm', punjabi:'ਤਜਰਬਾ', starred: false, english:'experience', audioId:'voc0911'},
                { id:12, gender: 'f', punjabi:'ਉਮੀਦ', starred: false, english:'hope', audioId:'voc0912'},
                { id:13, gender: 'f', punjabi:'ਿਦਲਚਸਪੀ', starred: false, english:'interest', audioId:'voc0913'},
                { id:14, gender: 'f', punjabi:'ਰੁਚੀ', starred: false, english:'interest', audioId:'voc0914'},
                { id:15, gender: 'm', punjabi:'ਮੌਕਾ', starred: false, english:'opportunity', audioId:'voc0915'},
                { id:16, gender: 'f', punjabi:'ਸੰਭਾਵਨਾ', starred: false, english:'possibility', audioId:'voc0916'},
                { id:17, gender: 'f', punjabi:'ਨੌਕਰੀ', starred: false, english:'job', audioId:'voc0917'},
                { id:18, gender: 'f', punjabi:'ਖੋਜ', starred: false, english:'research', audioId:'voc0918'},
                { id:19, gender: 'm', punjabi:'ਿਵਾ', starred: false, english:'subject', audioId:'voc0919'},
                { id:20, gender: 'm', punjabi:'ਉਮੀਦਵਾਰ', starred: false, english:'candidate', audioId:'voc0920'},
                { id:21, gender: 'm', punjabi:'ਥੈਲਾ', starred: false, english:'bag', audioId:'voc0921'},
                { id:22, gender: 'f', punjabi:'ਉਪਾਧੀ', starred: false, english:'degree', audioId:'voc09022'},
                { id:23, gender: 'm', punjabi:'ਿਵਭਾਗ', starred: false, english:'department', audioId:'voc0923'},
                { id:24, gender: 'm', punjabi:'ਿਵਚਾਰ', starred: false, english:'idea', audioId:'voc0924'},
                { id:25, gender: 'f', punjabi:'ਜਾਣਕਾਰੀ', starred: false, english:'knowledge', audioId:'voc0925'},
                { id:26, gender: 'f', punjabi:'ਦੁਨੀਆ', starred: false, english:'world', audioId:'voc0926'},
                { id:27, gender: '', punjabi:'ਵਿਦਆਰਥੀ', starred: false, english:'student', audioId:'voc0927'},
                { id:28, gender: 'm', punjabi:'ਵੇਰਵਾ', starred: false, english:'detail', audioId:'voc0928'},
                { id:29, gender: 'f', punjabi:'ਦੋਸਤੀ', starred: false, english:'friendship', audioId:'voc0929'},
                { id:30, gender: 'f', punjabi:'ਤਰਜੀਹ', starred: false, english:'preference/importance', audioId:'voc0930'},
                { id:31, gender: 'f', punjabi:'ਿਜ਼ੰਦਗੀ', starred: false, english:'life', audioId:'voc0931'},
            ],
        Verbs:
            [
                { id:1, gender: '', punjabi:'ਦਾਖਲਾ ਲੈਣਾ', starred: false, english:'to be admitted', audioId:'voc0945'},
                { id:2, gender: '', punjabi:'ਪਤਾ ਹੋਣਾ', starred: false, english:'to know', audioId:'voc0946'},
                { id:3, gender: '', punjabi:'ਿਸਖਣਾ', starred: false, english:'to learn', audioId:'voc0947'},
                { id:4, gender: '', punjabi:'ਅੱਗੇਵਧਣਾ', starred: false, english:'to move forward/to increase', audioId:'voc0948'},
                { id:5, gender: '', punjabi:'ਿਹੱਸਾ ਲੈਣਾ', starred: false, english:'to participate', audioId:'voc0949'},
                { id:6, gender: '', punjabi:'ਸੋਚਣਾ', starred: false, english:'to think', audioId:'voc0950'},
                { id:7, gender: '', punjabi:'ਲੰਘਣਾ', starred: false, english:'to pass', audioId:'voc0951'},
                { id:8, gender: '', punjabi:'ਛੱਡਣਾ', starred: false, english:'to leave', audioId:'voc0952'},
                { id:9, gender: '', punjabi:'ਪੈਣਾ', starred: false, english:'to have to do', audioId:'voc0953'},
                { id:10, gender: '', punjabi:'ਭੇਜਣਾ', starred: false, english:'to send', audioId:'voc0954'},
            ],
    },
    */