export const vocabularyData = {
    "Family":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਖੁਸ਼', starred: false, english:'happy', audioId:'voc0201'},
                { id:2, gender: '', punjabi:'ਦੋਵੇਂ', starred: false, english:'both', audioId:'voc0202'},
                { id:3, gender: '', punjabi:'ਇਕੱਠੇ', starred: false, english:'together', audioId:'voc0203'},
                { id:4, gender: '', punjabi:'ਵੱਡਾ', starred: false, english:'big or older', audioId:'voc0204'},
                { id:5, gender: '', punjabi:'ਛੋਟਾ', starred: false, english:'small or younger', audioId:'voc0205'}, 
            ],
        Nouns:
            [
                { id:6, gender: 'm', punjabi:'ਘਰ', starred: false, english:'home', audioId:'voc0206'},
                { id:7, gender: 'f', punjabi:'ਗੱਲਬਾਤ', starred: false, english:'conversation', audioId:'voc0207'},
                { id:8, gender: 'm', punjabi:'ਪਿਆਰ', starred: false, english:'love', audioId:'voc0208'},
                { id:9, gender: 'm', punjabi:'ਕੰਮ', starred: false, english:'work', audioId:'voc0209'},
                { id:10, gender: 'f', punjabi:'ਮਦਦ', starred: false, english:'help', audioId:'voc0210'},
                { id:11, gender: 'm', punjabi:'ਬਜ਼ੁਰਗ', starred: false, english:'elder', audioId:'voc0211'},
                { id:12, gender: 'm', punjabi:'ਡਾਕਟਰ', starred: false, english:'physician', audioId:'voc0212'},
                { id:13, gender: 'm', punjabi:'ਅਧਿਆਪਕ', starred: false, english:'teacher', audioId:'voc0213'},
                { id:14, gender: 'm', punjabi:'ਸਕੂਲ', starred: false, english:'school', audioId:'voc0214'},
                { id:15, gender: 'f', punjabi:'ਸੈਰ', starred: false, english:'stroll', audioId:'voc0215'},
                { id:16, gender: 'm', punjabi:'ਰਿਸ਼ਤੇਦਾਰ', starred: false, english:'relatives', audioId:'voc0216'},
                { id:17, gender: 'm', punjabi:'ਪਰਿਵਾਰ', starred: false, english:'family', audioId:'voc0217'},
                { id:18, gender: 'm', punjabi:'ਜੀਅ', starred: false, english:'family members', audioId:'voc0218'},
                { id:19, gender: 'f', punjabi:'ਮਾਤਾ/ਮਾਂ', starred: false, english:'mother', audioId:'voc0219'},
                { id:20, gender: 'm', punjabi:'ਪਿਤਾ', starred: false, english:'father', audioId:'voc0220'},
                { id:21, gender: 'm', punjabi:'ਭਰਾ', starred: false, english:'brother', audioId:'voc0221'},
                { id:22, gender: 'f', punjabi:'ਭੈਣ', starred: false, english:'sister', audioId:'voc0222'},
                { id:23, gender: 'f', punjabi:'ਧੀ', starred: false, english:'daughter', audioId:'voc0223'},
                { id:24, gender: 'm', punjabi:'ਪੁੱਤਰ', starred: false, english:'son', audioId:'voc0224'},
                { id:25, gender: 'm', punjabi:'ਪਤੀ', starred: false, english:'husband', audioId:'voc0225'},
                { id:26, gender: 'f', punjabi:'ਪਤਨੀ', starred: false, english:'wife', audioId:'voc0226'},
                { id:27, gender: 'f', punjabi:'ਨਾਨੀ', starred: false, english:'maternal grandmother', audioId:'voc0227'},
                { id:28, gender: 'm', punjabi:'ਨਾਨਾ', starred: false, english:'maternal grandfather', audioId:'voc0228'},
                { id:29, gender: 'f', punjabi:'ਮਾਸੀ', starred: false, english:'mother’s sister', audioId:'voc0229'},
                { id:30, gender: 'm', punjabi:'ਮਾਮਾ', starred: false, english:'mother’s brother', audioId:'voc0230'},
                { id:31, gender: 'f', punjabi:'ਮਾਮੀ', starred: false, english:'mama’s wife', audioId:'voc0231'},
                { id:32, gender: 'f', punjabi:'ਦਾਦੀ', starred: false, english:'paternal grandmother', audioId:'voc0232'},
                { id:33, gender: 'm', punjabi:'ਦਾਦਾ', starred: false, english:'paternal grandfather', audioId:'voc0233'},
                { id:34, gender: 'm', punjabi:'ਚਾਚਾ', starred: false, english:'father’s younger brother', audioId:'voc0234'},
                { id:35, gender: 'f', punjabi:'ਚਾਚੀ', starred: false, english:'chacha’s wife', audioId:'voc0235'},
            ],
        Verbs:
            [
                { id:36, gender: '', punjabi:'ਹੋਣਾ', starred: false, english:'to be', audioId:'voc0236'},
                { id:37, gender: '', punjabi:'ਕਰਨਾ', starred: false, english:'to do', audioId:'voc0237'},
                { id:38, gender: '', punjabi:'ਖੇਡਣਾ', starred: false, english:'to play', audioId:'voc0238'},
                { id:39, gender: '', punjabi:'ਪੜ੍ਹਨਾ', starred: false, english:'to study or read', audioId:'voc0239'}, 
            ]
    },
    "Home":
    {
        Nouns:
            [
                { id:1, gender: 'm', punjabi:'ਐਤਵਾਰ', starred: false, english:'Sunday', audioId:'voc0301'},
                { id:2, gender: 'm', punjabi:'ਸੋਮਵਾਰ', starred: false, english:'Monday', audioId:'voc0302'},
                { id:3, gender: 'm', punjabi:'ਮੰਗਲਵਾਰ', starred: false, english:'Tuesday', audioId:'voc0303'},
                { id:4, gender: 'm', punjabi:'ਬੁੱਧਵਾਰ', starred: false, english:'Wednesday', audioId:'voc0304'},
                { id:5, gender: 'm', punjabi:'ਵੀਰਵਾਰ', starred: false, english:'Thursday', audioId:'voc0305'},
                { id:6, gender: 'm', punjabi:'ਸ਼ੁੱਕਰਵਾਰ', starred: false, english:'Friday', audioId:'voc0306'},
                { id:7, gender: 'm', punjabi:'ਸ਼ਨਿੱਚਰਵਾਰ', starred: false, english:'Saturday', audioId:'voc0307'},
                { id:8, gender: '', punjabi:'ਅਪਾਰਟਮੈਂਟ', starred: false, english:'apartment', audioId:'voc0308'},
                { id:9, gender: 'm', punjabi:'ਕਮਰਾ', starred: false, english:'room', audioId:'voc0309'},
                { id:10, gender: 'f', punjabi:'ਥਾਂ', starred: false, english:'space, place', audioId:'voc0310'},
                { id:11, gender: 'f', punjabi:'ਬੈਠਕ', starred: false, english:'sitting room', audioId:'voc0311'},
                { id:12, gender: 'f', punjabi:'ਰਸੋਈ', starred: false, english:'kitchen', audioId:'voc0312'},
                { id:13, gender: 'm', punjabi:'ਬੈੱਡਰੂਮ', starred: false, english:'bedroom', audioId:'voc0313'},
                { id:14, gender: 'm', punjabi:'ਗ਼ੁਸਲਖ਼ਾਨਾ', starred: false, english:'bathroom', audioId:'voc0314'},
                { id:15, gender: 'm', punjabi:'ਵਿਹੜਾ', starred: false, english:'yard', audioId:'voc0315'},
                { id:16, gender: 'f', punjabi:'ਸੜਕ', starred: false, english:'road, street', audioId:'voc0316'},
                { id:17, gender: 'f', punjabi:'ਛੱਤ', starred: false, english:'roof, ceiling', audioId:'voc0317'},
                { id:18, gender: 'm', punjabi:'ਦਰਵਾਜਾ', starred: false, english:'door', audioId:'voc0318'},
                { id:19, gender: 'f', punjabi:'ਖਿੜਕੀ', starred: false, english:'window', audioId:'voc0319'},
                { id:20, gender: 'f', punjabi:'ਚਾਹ', starred: false, english:'tea', audioId:'voc0320'},
                { id:21, gender: '', punjabi:'ਫਰਨੀਚਰ', starred: false, english:'furniture', audioId:'voc0321'},
                { id:22, gender: '', punjabi:'ਬੁਰਸ਼', starred: false, english:'brush', audioId:'voc0322'},
                { id:23, gender: 'm', punjabi:'ਕੱਪੜੇ', starred: false, english:'clothes', audioId:'vvoc0323'},
                { id:24, gender: 'm', punjabi:'ਨਾਸ਼ਤਾ', starred: false, english:'breakfast', audioId:'voc0324'},
                { id:25, gender: 'f', punjabi:'ਸਫ਼ਾਈ', starred: false, english:'cleanliness', audioId:'voc0325'},
                { id:26, gender: 'm', punjabi:'ਅਰਾਮ', starred: false, english:'rest', audioId:'voc0326'},
                { id:27, gender: 'f', punjabi:'ਰਾਤ', starred: false, english:'night', audioId:'voc0327'},
                { id:28, gender: 'f', punjabi:'ਸਵੇਰ', starred: false, english:'morning', audioId:'voc0328'},
                { id:29, gender: 'f', punjabi:'ਸ਼ਾਮ', starred: false, english:'evening', audioId:'voc0329'},
                { id:30, gender: 'f', punjabi:'ਦੁਪਹਿਰ', starred: false, english:'at noon', audioId:'voc0330'},
                { id:31, gender: '', punjabi:'ਵਜੇ', starred: false, english:'o clock', audioId:'voc0332'},
            ],
        Verbs:
            [
                { id:32, gender: '', punjabi:'ਜਾਗਣਾ', starred: false, english:'to wake up', audioId:'voc0333'},
                { id:33, gender: '', punjabi:'ਬੈਠਣਾ', starred: false, english:'to sit', audioId:'voc0334'},
                { id:34, gender: '', punjabi:'ਦੇਖਣਾ', starred: false, english:'to see', audioId:'voc0335'},
                { id:35, gender: '', punjabi:'ਖਾਣਾ', starred: false, english:'to eat', audioId:'voc0336'},
                { id:36, gender: '', punjabi:'ਜਾਣਾ', starred: false, english:'to go', audioId:'voc0337'},
                { id:37, gender: '', punjabi:'ਧੋਣਾ', starred: false, english:'to wash', audioId:'voc0338'},
                { id:38, gender: '', punjabi:'ਸੌਣਾ', starred: false, english:'to sleep', audioId:'voc0339'},
                { id:39, gender: '', punjabi:'ਆਉਣਾ', starred: false, english:'to come', audioId:'voc0340'},
                { id:40, gender: '', punjabi:'ਨਹਾਉਣਾ', starred: false, english:'to take a shower', audioId:'voc0341'},
                { id:41, gender: '', punjabi:'ਬਣਾਉਣਾ', starred: false, english:'to make', audioId:'voc0342'},
                { id:42, gender: '', punjabi:'ਚਲਾਉਣਾ', starred: false, english:'to start or drive', audioId:'voc0343'},
                { id:43, gender: '', punjabi:'ਰਹਿਣਾ', starred: false, english:'to live', audioId:'voc0344'},
            ]
    },
    "Body & Health":
    {
        Adjectives:
            [
                { id:1, gender: '', punjabi:'ਤੰਦਰੁਸਤ', starred: false, english:'healthy', audioId:'voc0430'},
                { id:2, gender: '', punjabi:'ਉਦਾਸ', starred: false, english:'sad', audioId:'voc0431'},
                { id:3, gender: '', punjabi:'ਬਿਮਾਰ', starred: false, english:'sick', audioId:'voc0432'},
                { id:4, gender: '', punjabi:'ਢਿੱਲਾ', starred: false, english:'unwell', audioId:'voc0433'},
                { id:5, gender: '', punjabi:'ਕਮਜ਼ੋਰ', starred: false, english:'weak', audioId:'voc0434'},
            ],
        Nouns:
            [
                { id:6, gender: 'm', punjabi:'ਗੁੱਸਾ', starred: false, english:'anger', audioId:'voc0401'},
                { id:7, gender: 'f', punjabi:'ਘਬਰਾਹਟ', starred: false, english:'anxiety', audioId:'voc0402'},
                { id:8, gender: 'f', punjabi:'ਬੇਚੈਨੀ', starred: false, english:'restlessness', audioId:'voc0403'},
                { id:9, gender: '', punjabi:'ਸਟਰੈੱਸ', starred: false, english:'stress', audioId:'voc0404'},
                { id:10, gender: '', punjabi:'ਟੈਨਸ਼ਨ', starred: false, english:'tension', audioId:'voc0405'},
                { id:11, gender: 'm', punjabi:'ਫ਼ਿਕਰ', starred: false, english:'worry', audioId:'voc0406'},
                { id:12, gender: 'm', punjabi:'ਜ਼ੁਕਾਮ', starred: false, english:'bad cold', audioId:'voc0407'},
                { id:13, gender: 'f', punjabi:'ਠੰਢ', starred: false, english:'cold', audioId:'voc0408'},
                { id:14, gender: 'f', punjabi:'ਖੰਘ', starred: false, english:'cough', audioId:'voc0409'},
                { id:15, gender: 'm', punjabi:'ਥਕਾਵਟ', starred: false, english:'fatigue', audioId:'voc0410'},
                { id:16, gender: 'm', punjabi:'ਬੁਖਾਰ', starred: false, english:'fever', audioId:'voc0411'},
                { id:17, gender: 'f', punjabi:'ਛਿੱਕ', starred: false, english:'sneeze', audioId:'voc0412'},
                { id:18, gender: 'f', punjabi:'ਜਾਂਚ', starred: false, english:'diagnosis', audioId:'voc0413'},
                { id:19, gender: 'f', punjabi:'ਸਿਰ ਦਰਦ', starred: false, english:'headache', audioId:'voc0414'},
                { id:20, gender: 'f', punjabi:'ਸਿਹਤ', starred: false, english:'health', audioId:'voc0415'},
                { id:21, gender: 'm', punjabi:'ਦਿਲ', starred: false, english:'heart', audioId:'voc0416'},
                { id:22, gender: 'f', punjabi:'ਗਰਮੀ', starred: false, english:'heat, summer', audioId:'voc0417'},
                { id:23, gender: 'f', punjabi:'ਭੁੱਖ', starred: false, english:'hunger', audioId:'voc0418'},
                { id:24, gender: 'f', punjabi:'ਦਵਾਈ', starred: false, english:'medicine', audioId:'voc0419'},
                { id:25, gender: 'm', punjabi:'ਮਨ', starred: false, english:'mind', audioId:'vvoc0420'},
                { id:26, gender: 'f', punjabi:'ਗੋਲੀ', starred: false, english:'pill', audioId:'voc0421'},
                { id:27, gender: 'f', punjabi:'ਤ੍ਰੇਹ', starred: false, english:'thirst', audioId:'voc0422'},
                { id:28, gender: 'f', punjabi:'ਨੀਂਦ', starred: false, english:'sleep', audioId:'voc0423'},
                { id:29, gender: 'm', punjabi:'ਖਿਆਲ', starred: false, english:'thought', audioId:'voc0424'},
                { id:30, gender: 'm', punjabi:'ਗਲਾ', starred: false, english:'throat', audioId:'voc0425'},
                { id:31, gender: 'm', punjabi:'ਇਲਾਜ', starred: false, english:'treatment', audioId:'voc0426'},
                { id:32, gender: 'f', punjabi:'ਅੱਖਾਂ', starred: false, english:'eyes', audioId:'voc0427'},
                { id:33, gender: 'm', punjabi:'ਜੀਵਨ', starred: false, english:'life', audioId:'voc0428'},
                { id:34, gender: 'f', punjabi:'ਮਾਸਪੇਸ਼ੀਆਂ', starred: false, english:'muscle', audioId:'voc0429'}, 
            ],
        Verbs:
            [
                { id:35, gender: '', punjabi:'ਰੋਣਾ', starred: false, english:'to cry', audioId:'voc0435'},
                { id:36, gender: '', punjabi:'ਪੀਣਾ', starred: false, english:'to drink', audioId:'voc0436'},
                { id:37, gender: '', punjabi:'ਦਿਲ ਕਰਨਾ', starred: false, english:'to feel like', audioId:'voc0437'},
                { id:38, gender: '', punjabi:'ਲੱਗਣਾ', starred: false, english:'to feel, appear or seem', audioId:'voc0438'},
                { id:39, gender: '', punjabi:'ਦੁਖਣਾ', starred: false, english:'To hurt', audioId:'voc0439'},
                { id:40, gender: '', punjabi:'ਹੋਣਾ', starred: false, english:'to occur', audioId:'voc0440'},
                { id:41, gender: '', punjabi:'ਲੈਣਾ', starred: false, english:'to take', audioId:'voc0441'},
            ]
    },
}

/*
export const vocabularyData = [
    { id:1,  module: 2, group:'Adjectives', gender:'',  punjabi:'ਖੁਸ਼', tranlit:'khush', english:'happy', audioId:'voc0201'},
    { id:2,  module: 2, group:'Adjectives', gender: '', punjabi:'ਦੋਵੇਂ', tranlit:'dovem', english:'both', audioId:'voc0202'},
    { id:3,  module: 2, group:'Adjectives', gender: '',  punjabi:'ਇਕੱਠੇ', tranlit:'ikaṭhṭhe', english:'together', audioId:'voc0203'},
    { id:4,  module: 2, group:'Adjectives', gender: '',  punjabi:'ਵੱਡਾ', tranlit:'vaḍḍā', english:'big/older', audioId:'voc0204'},
    { id:5,  module: 2, group:'Adjectives', gender: '',  punjabi:'ਛੋਟਾ', tranlit:'choṭā', english:'small/ younger', audioId:'voc0205'},
    { id:6,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਘਰ', tranlit:'ghar', english:'home', audioId:'voc0206'},
    { id:7,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਗੱਲਬਾਤ', tranlit:'gallbāt', english:'conversation', audioId:'voc0207'},
    { id:8,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਪਿਆਰ', tranlit:'piār', english:'love', audioId:'voc0208'},
    { id:9,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਕੰਮ', tranlit:'kaḿ', english:'work', audioId:'voc0209'},
    { id:10,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਮਦਦ', tranlit:'ਮਦਦ', english:'help', audioId:'voc0210'},
    { id:11,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਬਜ਼ੁਰਗ', tranlit:'bzurg', english:'elder', audioId:'voc0211'},
    { id:12,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਡਾਕਟਰ', tranlit:'ḍākṭr', english:'physician', audioId:'voc0212'},
    { id:13,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਅਧਿਆਪਕ', tranlit:'adhiāpk', english:'teacher', audioId:'voc0213'},
    { id:14,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਸਕੂਲ', tranlit:'skūl', english:'school', audioId:'voc0214'},
    { id:15,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਸੈਰ', tranlit:'sair', english:'stroll', audioId:'voc0215'},
    { id:16,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਰਿਸ਼ਤੇਦਾਰ', tranlit:'rishatēdār', english:'relatives', audioId:'voc0216'},
    { id:17,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਪਰਿਵਾਰ', tranlit:'parivār', english:'family', audioId:'voc0217'},
    { id:18,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਜੀਅ', tranlit:'jīa', english:'family members', audioId:'voc0218'},
    { id:19,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਮਾਂ/ਮਾਤਾ', tranlit:'māṃ/mātā', english:'mother', audioId:'voc0219'},
    { id:20,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਪਿਤਾ', tranlit:'pitā', english:'father', audioId:'voc0220'},
    { id:21,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਭਰਾ', tranlit:'bharā', english:'brother', audioId:'voc0221'},
    { id:22,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਭੈਣ', tranlit:'bhaiṇ', english:'sister', audioId:'voc0222'},
    { id:23,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਧੀ', tranlit:'dhī', english:'daughter', audioId:'voc0223'},
    { id:24,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਪੁੱਤਰ', tranlit:'puttr', english:'son', audioId:'voc0224'},
    { id:25,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਪਤੀ', tranlit:'patī', english:'husband', audioId:'voc0225'},
    { id:26,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਪਤਨੀ', tranlit:'patnī', english:'wife', audioId:'voc0226'},
    { id:27,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਨਾਨੀ', tranlit:'nānī', english:'maternal grandmother', audioId:'voc0227'},
    { id:28,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਨਾਨਾ', tranlit:'nānā', english:'maternal grandfather', audioId:'voc0228'},
    { id:29,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਮਾਸੀ', tranlit:'māsī', english:'mother’s sister', audioId:'voc0229'},
    { id:30,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਮਾਮਾ', tranlit:'māmā', english:'mother’s brother', audioId:'voc0230'},
    { id:31,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਮਾਮੀ', tranlit:'māmī', english:'mama’s wife', audioId:'voc0231'},
    { id:32,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਦਾਦੀ', tranlit:'dādī', english:'paternal grandmother', audioId:'voc0232'},
    { id:33,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਦਾਦਾ', tranlit:'dādā', english:'paternal grandfather', audioId:'voc0233'},
    { id:34,  module: 2, group:'Nouns', gender: 'm',  punjabi:'ਚਾਚਾ', tranlit:'chāchā', english:'father’s younger brother', audioId:'voc0234'},
    { id:35,  module: 2, group:'Nouns', gender: 'f',  punjabi:'ਚਾਚੀ', tranlit:'chāchī', english:'chacha’s wife', audioId:'voc0235'},
    { id:36,  module: 2, group:'Verbs', gender: '',  punjabi:'ਹੋਣਾ', tranlit:'hōṇā', english:'to be', audioId:'voc0236'},
    { id:37,  module: 2, group:'Verbs', gender: '',  punjabi:'ਕਰਨਾ', tranlit:'karnā', english:'to do', audioId:'voc0237'},
    { id:38,  module: 2, group:'Verbs', gender: '',  punjabi:'ਖੇਡਣਾ', tranlit:'kheḍṇā', english:'to play', audioId:'voc0238'},
    { id:39,  module: 2, group:'Verbs', gender: '',  punjabi:'ਪੜ੍ਹਨਾ', tranlit:'paṛhnā', english:'to study/to read', audioId:'voc0239'},

    { id:40,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਐਤਵਾਰ', tranlit:'', english:'Sunday', audioId:'voc0301'},
    { id:41,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਸੋਮਵਾਰ', tranlit:'', english:'Monday', audioId:'voc0302'},
    { id:42,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਮੰਗਲਵਾਰ', tranlit:'', english:'Tuesday', audioId:'voc0303'},
    { id:43,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਬੁੱਧਵਾਰ', tranlit:'', english:'Wednesday', audioId:'voc0304'},
    { id:44,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਵੀਰਵਾਰ', tranlit:'', english:'Thursday', audioId:'voc0305'},
    { id:45,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਸ਼ੁੱਕਰਵਾਰ', tranlit:'', english:'Friday', audioId:'voc0306'},
    { id:46,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਸ਼ਨਿੱਚਰਵਾਰ', tranlit:'', english:'Saturday', audioId:'voc0307'},
    { id:47,  module: 3, group:'Nouns', gender: '',  punjabi:'ਅਪਾਰਟਮੈਂਟ', tranlit:'', english:'apartment', audioId:'voc0308'},
    { id:48,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਕਮਰਾ', tranlit:'', english:'room', audioId:'voc0309'},
    { id:49,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਥਾਂ', tranlit:'', english:'space/place', audioId:'voc0310'},
    { id:50,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਬੈਠਕ', tranlit:'', english:'sitting room', audioId:'voc0311'},
    { id:51,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਰਸੋਈ', tranlit:'', english:'kitchen', audioId:'voc0312'},
    { id:52,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਸੌਣ ਵਾਲਾ ਕਮਰਾ/ ਬੈੱਡਰੂਮ', tranlit:'', english:'to study/to read', audioId:'voc0313'},
    { id:53,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਗ਼ੁਸਲਖ਼ਾਨਾ', tranlit:'', english:'bathroom', audioId:'voc0314'},
    { id:54,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਵਿਹੜਾ', tranlit:'', english:'yard', audioId:'voc0315'},
    { id:55,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਸੜਕ', tranlit:'', english:'road/street', audioId:'voc0316'},
    { id:56,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਛੱਤ', tranlit:'', english:'roof/ceiling', audioId:'voc0317'},
    { id:57,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਦਰਵਾਜਾ', tranlit:'', english:'door', audioId:'voc0318'},
    { id:58,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਖਿੜਕੀ', tranlit:'', english:'window', audioId:'voc0319'},
    { id:59,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਚਾਹ', tranlit:'', english:'tea', audioId:'voc0320'},
    { id:60,  module: 3, group:'Nouns', gender: '',  punjabi:'ਫਰਨੀਚਰ', tranlit:'', english:'furniture', audioId:'voc0321'},
    { id:61,  module: 3, group:'Nouns', gender: '',  punjabi:'ਬੁਰਸ਼', tranlit:'', english:'brush', audioId:'voc0322'},
    { id:62,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਕੱਪੜੇ', tranlit:'', english:'clothes', audioId:'vvoc0323'},
    { id:63,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਨਾਸ਼ਤਾ', tranlit:'', english:'breakfast', audioId:'voc0324'},
    { id:64,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਸਫ਼ਾਈ', tranlit:'', english:'cleanliness', audioId:'voc0325'},
    { id:65,  module: 3, group:'Nouns', gender: 'm',  punjabi:'ਅਰਾਮ', tranlit:'', english:'rest', audioId:'voc0326'},
    { id:66,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਰਾਤ', tranlit:'', english:'night', audioId:'voc0327'},
    { id:67,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਸਵੇਰ', tranlit:'', english:'morning', audioId:'voc0328'},
    { id:68,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਸ਼ਾਮ', tranlit:'', english:'evening', audioId:'voc0329'},
    { id:69,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਦੁਪਹਿਰ', tranlit:'', english:'at noon', audioId:'voc0330'},
    { id:70,  module: 3, group:'Nouns', gender: 'f',  punjabi:'ਰਾਤ', tranlit:'', english:'in the night', audioId:'voc0331'},
    { id:71,  module: 3, group:'Nouns', gender: '',  punjabi:'ਵਜੇ', tranlit:'', english:'o clock', audioId:'voc0332'},
    { id:72,  module: 3, group:'Verbs', gender: '',  punjabi:'ਜਾਗਣਾ', tranlit:'', english:'to wake up', audioId:'voc0333'},
    { id:73,  module: 3, group:'Verbs', gender: '',  punjabi:'ਬੈਠਣਾ', tranlit:'', english:'to sit', audioId:'voc0334'},
    { id:74,  module: 3, group:'Verbs', gender: '',  punjabi:'ਦੇਖਣਾ', tranlit:'', english:'to see', audioId:'voc0335'},
    { id:75,  module: 3, group:'Verbs', gender: '',  punjabi:'ਖਾਣਾ', tranlit:'', english:'to eat', audioId:'voc0336'},
    { id:76,  module: 3, group:'Verbs', gender: '',  punjabi:'ਜਾਣਾ/ ਜਾਹ', tranlit:'', english:'to go', audioId:'voc0337'},
    { id:77,  module: 3, group:'Verbs', gender: '',  punjabi:'ਧੋਣਾ', tranlit:'', english:'to wash', audioId:'voc0338'},
    { id:78,  module: 3, group:'Verbs', gender: '',  punjabi:'ਸੌਣਾ', tranlit:'', english:'to sleep', audioId:'voc0339'},
    { id:79,  module: 3, group:'Verbs', gender: '',  punjabi:'ਆਉਣਾ', tranlit:'', english:'to come', audioId:'voc0340'},
    { id:80,  module: 3, group:'Verbs', gender: '',  punjabi:'ਨਹਾਉਣਾ', tranlit:'', english:'to take a shower', audioId:'voc0341'},
    { id:81,  module: 3, group:'Verbs', gender: '',  punjabi:'ਬਣਾਉਣਾ', tranlit:'', english:'to make', audioId:'voc0342'},
    { id:82,  module: 3, group:'Verbs', gender: '',  punjabi:'ਚਲਾਉਣਾ', tranlit:'', english:'to start (a machine)/to drive', audioId:'voc0343'},
    { id:83,  module: 3, group:'Verbs', gender: '',  punjabi:'ਰਹਿਣਾ', tranlit:'', english:'to live', audioId:'voc0344'},

   { id:84,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਗੁੱਸਾ', tranlit:'', english:'anger', audioId:'voc0401'},
   { id:85,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਘਬਰਾਹਟ', tranlit:'', english:'anxiety', audioId:'voc0402'},
   { id:86,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਬੇਚੈਨੀ', tranlit:'', english:'restlessness', audioId:'voc0403'},
   { id:87,  module: 4, group:'Nouns', gender: '',  punjabi:'ਸਟਰੈੱਸ', tranlit:'', english:'stress', audioId:'voc0404'},
   { id:88,  module: 4, group:'Nouns', gender: '',  punjabi:'ਟੈਨਸ਼ਨ', tranlit:'', english:'tension', audioId:'voc0405'},
   { id:89,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਫ਼ਿਕਰ/ ਚਿੰਤਾ', tranlit:'', english:'worry', audioId:'voc0406'},
   { id:90,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਜ਼ੁਕਾਮ', tranlit:'', english:'bad cold', audioId:'voc0407'},
   { id:91,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਠੰਢ', tranlit:'', english:'cold', audioId:'voc0408'},
   { id:92,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਖੰਘ', tranlit:'', english:'cough', audioId:'voc0409'},
   { id:93,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਥਕਾਵਟ', tranlit:'', english:'fatigue', audioId:'voc0410'},
   { id:94,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਬੁਖਾਰ', tranlit:'', english:'fever', audioId:'voc0411'},
   { id:95,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਛਿੱਕ', tranlit:'', english:'sneeze', audioId:'voc0412'},
   { id:96,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਜਾਂਚ', tranlit:'', english:'diagnosis', audioId:'voc0413'},
   { id:97,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਸਿਰ ਦਰਦ', tranlit:'', english:'headache', audioId:'voc0414'},
   { id:98,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਸਿਹਤ', tranlit:'', english:'health', audioId:'voc0415'},
   { id:99,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਦਿਲ', tranlit:'', english:'heart', audioId:'voc0416'},
   { id:100,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਗਰਮੀ', tranlit:'', english:'heat/summer', audioId:'voc0417'},
   { id:101,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਭੁੱਖ', tranlit:'', english:'hunger', audioId:'voc0418'},
   { id:102,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਦਵਾਈ', tranlit:'', english:'medicine', audioId:'voc0419'},
   { id:103,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਮਨ', tranlit:'', english:'mind', audioId:'vvoc0420'},
   { id:104,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਗੋਲੀ', tranlit:'', english:'pill', audioId:'voc0421'},
   { id:105,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਪਿਆਸ/ ਤ੍ਰੇਹ', tranlit:'', english:'thirst', audioId:'voc0422'},
   { id:106,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਨੀਂਦ', tranlit:'', english:'sleep', audioId:'voc0423'},
   { id:107,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਖਿਆਲ', tranlit:'', english:'thought', audioId:'voc0424'},
   { id:108,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਗਲਾ', tranlit:'', english:'throat', audioId:'voc0425'},
   { id:109,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਇਲਾਜ', tranlit:'', english:'treatment', audioId:'voc0426'},
   { id:110,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਅੱਖਾਂ', tranlit:'', english:'eyes', audioId:'voc0427'},
   { id:111,  module: 4, group:'Nouns', gender: 'm',  punjabi:'ਜੀਵਨ', tranlit:'', english:'life', audioId:'voc0428'},
   { id:112,  module: 4, group:'Nouns', gender: 'f',  punjabi:'ਮਾਸਪੇਸ਼ੀਆਂ', tranlit:'', english:'muscle', audioId:'voc0429'},
   { id:113,  module: 4, group:'Adjectives', gender: '',  punjabi:'ਤੰਦਰੁਸਤ', tranlit:'', english:'healthy', audioId:'voc0430'},
   { id:114,  module: 4, group:'Adjectives', gender: '',  punjabi:'ਉਦਾਸ', tranlit:'', english:'sad', audioId:'voc0431'},
   { id:115,  module: 4, group:'Adjectives', gender: '',  punjabi:'ਬਿਮਾਰ', tranlit:'', english:'sick', audioId:'voc0432'},
   { id:116,  module: 4, group:'Adjectives', gender: '',  punjabi:'ਢਿੱਲਾ', tranlit:'', english:'unwell', audioId:'voc0433'},
   { id:117,  module: 4, group:'Adjectives', gender: '',  punjabi:'ਕਮਜ਼ੋਰ', tranlit:'', english:'weak', audioId:'voc0434'},
   { id:118,  module: 4, group:'Verbs', gender: '',  punjabi:'ਰੋਣਾ', tranlit:'', english:'to cry', audioId:'voc0435'},
   { id:119,  module: 4, group:'Verbs', gender: '',  punjabi:'ਪੀਣਾ', tranlit:'', english:'to drink', audioId:'voc0436'},
   { id:120,  module: 4, group:'Verbs', gender: '',  punjabi:'ਦਿਲ ਕਰਨਾ', tranlit:'', english:'to feel like', audioId:'voc0437'},
   { id:121,  module: 4, group:'Verbs', gender: '',  punjabi:'ਲੱਗਣਾ', tranlit:'', english:'to feel/to appear/to seem', audioId:'voc0438'},
   { id:122,  module: 4, group:'Verbs', gender: '',  punjabi:'ਦੁਖਣਾ', tranlit:'', english:'To hurt', audioId:'voc0439'},
   { id:123,  module: 4, group:'Verbs', gender: '',  punjabi:'ਹੋਣਾ', tranlit:'', english:'to occur', audioId:'voc0440'},
   { id:124,  module: 4, group:'Verbs', gender: '',  punjabi:'ਲੈਣਾ', tranlit:'', english:'to take', audioId:'voc0441'},
*/
